# Generated by Django 3.0.7 on 2020-06-08 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_auto_20200606_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'get_latest_by': 'start_time'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
