# Generated by Django 3.0.7 on 2020-06-08 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0003_auto_20200608_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
