# Generated by Django 3.0.7 on 2020-06-08 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0004_auto_20200608_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
