# Generated by Django 3.0.7 on 2020-06-08 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0005_auto_20200608_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
